language: node_js
sudo: false
node_js:
- '0.11'
- '0.10'
before_script:
   - 'export CHROME_BIN=chromium-browser'
   - 'export DISPLAY=:99.0'
   - 'sh -e /etc/init.d/xvfb start'
   - 'npm install -g bower'
   - 'npm install -g gulp'
   - 'bower install'
after_script:
  - 'cat ./coverage/lcov-report/lcov.info | ./node_modules/coveralls/bin/coveralls.js' 
